# Generated by Django 6.0 on 2026-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_remove_book_author_remove_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='pages_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
